(function(){
 let runtime=null;
 const MUSIC_BASE='assets/audio/music/',SFX_BASE='assets/audio/sfx/';
 class Player{
  constructor(comp,hooks={}){this.comp=comp;this.hooks=hooks;this.index=Math.min(comp.playhead||0,comp.scenes.length-1);this.elapsed=0;this.playing=false;this.timer=null;this.activityTimer=null;this.startedAt=0;this.music=new Audio();this.music.loop=true;this.music.preload='auto';this.musicReady=null;this.audioNoticeShown=false;this.sfx=[];this.objectUrls=[];this.boundActivity=()=>this.showControls();this.boundKeys=e=>{this.showControls();if(e.code==='Space'){e.preventDefault();this.toggle()}if(e.code==='ArrowRight')this.next();if(e.code==='ArrowLeft')this.prev()};window.addEventListener('keydown',this.boundKeys)}
  scene(){return this.comp.scenes[this.index]}
  mount(){this.draw();this.updateControls();this.musicReady=this.loadMusic();const page=document.querySelector('.player-page');page?.addEventListener('pointermove',this.boundActivity);page?.addEventListener('pointerdown',this.boundActivity);return this}
  async loadMusic(){this.music.pause();this.music.removeAttribute('src');try{if(this.comp.musicSelection==='uploaded'){const ref=this.comp.uploadedAudio?.find(a=>a.role==='music');if(ref){const url=await AudioStore.url(ref.id);if(url){this.objectUrls.push(url);this.music.src=url}}}else this.music.src=MUSIC_BASE+(this.comp.musicSelection||'adventure')+'.wav';this.music.volume=this.comp.musicVolume??.45;if(this.music.src)this.music.load();return !!this.music.src}catch{this.friendly('Music is unavailable, but your movie can still play.');return false}}
  draw(){const s=this.scene(),screen=document.querySelector('#movieScreen');if(!screen||!s)return;screen.className=`movie-screen camera-${slug(s.cameraMotion)} transition-${slug(this.comp.transitionSettings.reducedMotion?'Fade':s.transitionIn)}`;screen.style.setProperty('--scene-duration',s.duration+'s');screen.style.setProperty('--scene1',s.background?.colors?.[0]||'#17265d');screen.style.setProperty('--scene2',s.background?.colors?.[1]||'#a45cf2');screen.innerHTML=sceneHTML(s,this.comp);document.querySelector('#sceneCounter').textContent=`${this.index+1} / ${this.comp.scenes.length}`;this.updateTimeline();if(this.playing){requestAnimationFrame(()=>screen.classList.add('scene-running'));this.speak();this.playSfx()}}
  play(){if(this.playing)return;this.playing=true;this.startedAt=performance.now()-this.elapsed*1000;this.draw();this.timer=setInterval(()=>this.tick(),100);this.updateControls();this.showControls();this.startMusic()}
  startMusic(){const attempt=()=>{if(!this.playing||!this.music.src)return;this.music.play().catch(()=>{if(!this.audioNoticeShown){this.audioNoticeShown=true;this.friendly('Your movie is playing without music. Tap Play once more if you want sound.')}})};attempt();this.musicReady?.then(ready=>{if(ready&&this.playing&&this.music.paused)attempt()}).catch(()=>{})}
  pause(){if(!this.playing)return;this.elapsed=(performance.now()-this.startedAt)/1000;this.playing=false;clearInterval(this.timer);this.timer=null;this.music.pause();if('speechSynthesis'in window)speechSynthesis.pause();this.updateControls();this.showControls()}
  toggle(){this.playing?this.pause():this.play()}
  tick(){const s=this.scene();this.elapsed=(performance.now()-this.startedAt)/1000;if(this.elapsed>=s.duration){if(this.index>=this.comp.scenes.length-1){this.finish();return}this.index++;this.elapsed=0;this.startedAt=performance.now();this.comp.playhead=this.index;this.draw()}this.updateControls()}
  next(){if(this.index<this.comp.scenes.length-1){this.index++;this.elapsed=0;this.startedAt=performance.now();this.comp.playhead=this.index;this.draw();this.updateControls()}}
  prev(){if(this.elapsed>2){this.elapsed=0}else if(this.index>0){this.index--;this.elapsed=0}this.startedAt=performance.now();this.comp.playhead=this.index;this.draw();this.updateControls()}
  restart(){this.index=0;this.elapsed=0;this.startedAt=performance.now();this.comp.playhead=0;if('speechSynthesis'in window)speechSynthesis.cancel();this.music.currentTime=0;this.draw();this.updateControls();if(!this.playing)this.play()}
  jump(i){if(i<0||i>=this.comp.scenes.length)return;this.index=i;this.elapsed=0;this.startedAt=performance.now();this.comp.playhead=i;this.draw();this.updateControls()}
  finish(){this.pause();this.comp.playhead=0;this.updateControls();this.hooks.onFinish?.()}
  updateControls(){const s=this.scene();if(!s)return;const total=MovieStudio.totalDuration(this.comp),before=this.comp.scenes.slice(0,this.index).reduce((n,x)=>n+x.duration,0),current=before+Math.min(this.elapsed,s.duration),pct=total?current/total*100:0;setText('#currentTime',format(current));setText('#totalTime',format(total));const bar=document.querySelector('#movieProgressFill');if(bar)bar.style.width=pct+'%';document.querySelectorAll('[data-player-action="toggle"]').forEach(play=>{play.classList.toggle('is-playing',this.playing);play.textContent=play.classList.contains('mobile-screen-play')?(this.playing?'❚❚':'▶'):(this.playing?'❚❚ PAUSE':'▶ PLAY')});this.comp.updatedDate=new Date().toISOString()}
  updateTimeline(){document.querySelectorAll('[data-player-scene]').forEach((x,i)=>x.classList.toggle('active',i===this.index))}
  setVolume(v){this.comp.musicVolume=Math.max(0,Math.min(1,Number(v)));this.music.volume=this.comp.musicVolume}
  toggleCaptions(){this.comp.narrationSettings.captions=!this.comp.narrationSettings.captions;this.draw()}
  toggleNarration(){this.comp.narrationSettings.enabled=!this.comp.narrationSettings.enabled;if(!this.comp.narrationSettings.enabled&&'speechSynthesis'in window)speechSynthesis.cancel();else if(this.playing)this.speak()}
  showControls(){const page=document.querySelector('.player-page');page?.classList.remove('controls-idle');clearTimeout(this.activityTimer);if(this.playing)this.activityTimer=setTimeout(()=>page?.classList.add('controls-idle'),2600)}
  speak(){if(!this.comp.narrationSettings.enabled||!('speechSynthesis'in window))return;const s=this.scene();speechSynthesis.cancel();const u=new SpeechSynthesisUtterance([s.title,s.narration,s.dialogue].filter(Boolean).join('. ')),n=this.comp.narrationSettings;u.rate=n.rate;u.pitch=n.pitch;u.volume=n.volume;const voices=speechSynthesis.getVoices();if(n.voice){const v=voices.find(x=>x.name===n.voice);if(v)u.voice=v}speechSynthesis.speak(u)}
  playSfx(){if(!this.comp.soundEffects)return;for(const cue of this.scene().soundEffects||[]){const delay=Math.max(0,(cue.time||0)*1000),id=setTimeout(()=>{if(!this.playing)return;const a=new Audio(SFX_BASE+cue.name+'.wav');a.volume=.55;a.play().catch(()=>{});this.sfx.push(a)},delay);this.sfx.push({timer:id,pause(){clearTimeout(id)}})}}
  friendly(msg){this.hooks.onMessage?.(msg)}
  cleanup(){this.pause();clearInterval(this.timer);clearTimeout(this.activityTimer);this.music.pause();this.music.src='';for(const x of this.sfx){if(x.timer)clearTimeout(x.timer);else x.pause?.()}this.sfx=[];if('speechSynthesis'in window)speechSynthesis.cancel();for(const url of this.objectUrls)URL.revokeObjectURL(url);this.objectUrls=[];const page=document.querySelector('.player-page');page?.removeEventListener('pointermove',this.boundActivity);page?.removeEventListener('pointerdown',this.boundActivity);window.removeEventListener('keydown',this.boundKeys)}
 }
 function sceneHTML(s,comp){const credits=s.sceneType==='credits',title=s.sceneType==='title',caption=comp.narrationSettings.captions,art=s.background?.image;return `${art?`<img class="movie-pdf-art" src="${escape(art)}" alt="Imported story artwork">`:`<div class="movie-atmosphere effect-${slug(s.visualEffects?.[0])}"></div><span class="movie-world">${s.background?.icon||'✦'}</span>${(s.characterLayers||[]).map((c,i)=>`<div class="movie-character ${c.image?'real-movie-star':''} motion-${slug(c.motion)}" style="--layer:${i}">${c.image?`<img src="${escape(c.image)}" alt="${escape(c.name)}">`:`<b>${escape(c.initial||c.name?.[0]||'?')}</b>`}<small>${escape(c.name)}</small></div>`).join('')}<div class="movie-props">${(s.propLayers||[]).map(p=>`<span class="motion-${slug(p.motion)}">${p.icon||'◆'}</span>`).join('')}</div>`}${title?`<div class="movie-title-card"><small>STORY SPARK CINEMA PRESENTS</small><h1>${escape(comp.title)}</h1><p>Starring ${escape(comp.characters?.[0]?.name||'Our Hero')}</p><b>A Story Spark Cinema Original</b></div>`:credits?`<div class="rolling-credits"><h2>${escape(comp.title)}</h2>${escape(s.narration).split('\n').map(x=>`<p>${x}</p>`).join('')}<strong>${escape(s.dialogue)}</strong></div>`:caption&&!art?`<div class="movie-captions text-${slug(s.textStyle)}"><small>${escape(s.background?.name||'Movie Stage')}</small><h2>${escape(s.title)}</h2><p>${escape(s.narration)}</p>${s.dialogue?`<blockquote>${escape(s.dialogue)}</blockquote>`:''}${s.objective?`<b>Objective: ${escape(s.objective)}</b>`:''}</div>`:''}`}
 function render(comp){return `<div class="player-page"><div class="player-marquee"><button class="btn ghost" data-player-action="exit">← EXIT MOVIE</button><div><div class="eyebrow">NOW PLAYING</div><h2>${escape(comp.title)}</h2></div><button class="btn gold export-movie-btn" data-export-movie>⬇ EXPORT MOVIE</button><span id="sceneCounter"></span></div><div class="mobile-movie-stage"><div id="movieScreen" class="movie-screen"></div><button class="mobile-screen-play" data-player-action="toggle" aria-label="Play or pause movie">▶</button></div><div class="player-controls"><div class="progress-line"><div id="movieProgressFill"></div></div><div class="control-row"><button data-player-action="restart" title="Restart">↻</button><button data-player-action="prev" title="Previous scene">◀</button><button id="playerPlay" class="play-main" data-player-action="toggle">▶ PLAY</button><button data-player-action="next" title="Next scene">▶</button><span><b id="currentTime">0:00</b> / <span id="totalTime">0:00</span></span><label>🔊 <input type="range" min="0" max="1" step=".05" value="${comp.musicVolume??.45}" data-player-volume></label><button class="text-control ${comp.narrationSettings.captions?'on':''}" data-player-action="captions">CC</button><button class="text-control ${comp.narrationSettings.enabled?'on':''}" data-player-action="narration">🎙 NARRATION</button><button data-player-action="skip-credits">SKIP CREDITS</button></div></div><div class="player-scene-strip">${comp.scenes.map((s,i)=>`<button data-player-scene="${i}"><span>${s.sceneType==='title'?'🎞️':s.sceneType==='credits'?'🏆':'🎬'}</span><small>${escape(s.title)}</small></button>`).join('')}</div></div>`}
 function mount(comp,hooks){runtime?.cleanup();runtime=new Player(comp,hooks).mount();return runtime}
 function cleanup(){runtime?.cleanup();runtime=null}
 const action=(name,value)=>{if(!runtime)return;if(name==='toggle')runtime.toggle();if(name==='restart')runtime.restart();if(name==='prev')runtime.prev();if(name==='next')runtime.next();if(name==='captions')runtime.toggleCaptions();if(name==='narration')runtime.toggleNarration();if(name==='skip-credits')runtime.jump(runtime.comp.scenes.length-1);if(name==='volume')runtime.setVolume(value)};
 const jump=i=>runtime?.jump(i);
 function format(sec){const s=Math.max(0,Math.floor(sec));return `${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}
 function slug(s){return String(s||'static').toLowerCase().replace(/[^a-z0-9]+/g,'-')}
 function escape(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
 function setText(sel,value){const e=document.querySelector(sel);if(e)e.textContent=value}
 window.CinemaPlayer={render,mount,cleanup,action,jump,format,get active(){return runtime}};
})();
