(function(){
 let active=null,portraitCache=new Map();
 const WIDTH=1280,HEIGHT=720,FPS=30;
 const escFile=s=>String(s||'story-spark-movie').replace(/[^a-z0-9-_]+/gi,'-').replace(/^-+|-+$/g,'').slice(0,70)||'story-spark-movie';
 const supported=()=>typeof MediaRecorder!=='undefined'&&typeof document.createElement('canvas').captureStream==='function';
 function overlay(title,total){let el=document.querySelector('#movieExportOverlay');if(!el){el=document.createElement('div');el.id='movieExportOverlay';el.className='export-overlay';document.body.appendChild(el)}el.innerHTML=`<div class="export-box"><div class="export-reel">🎞️</div><h2>EXPORTING YOUR MOVIE</h2><p>${safe(title)}</p><div class="export-progress"><i></i></div><strong>Preparing the opening scene…</strong><small>Keep this tab open. Your ${format(total)} movie exports in real time.</small><button class="btn ghost" type="button">CANCEL EXPORT</button></div>`;el.classList.add('open');el.querySelector('button').onclick=()=>cancel();return el}
 function update(el,pct,message){const bar=el?.querySelector('.export-progress i'),label=el?.querySelector('strong');if(bar)bar.style.width=Math.max(0,Math.min(100,pct))+'%';if(label)label.textContent=message}
 function closeOverlay(){const el=document.querySelector('#movieExportOverlay');if(el)el.classList.remove('open')}
 function cancel(){if(active)active.cancelled=true}
 function image(src){return new Promise(resolve=>{if(!src)return resolve(null);const img=new Image();img.onload=()=>resolve(img);img.onerror=()=>resolve(null);img.src=src})}
 function roundRect(ctx,x,y,w,h,r){ctx.beginPath();ctx.roundRect(x,y,w,h,r);ctx.fill()}
 function wrap(ctx,text,x,y,maxWidth,lineHeight,maxLines=5){const words=String(text||'').split(/\s+/),lines=[];let line='';for(const word of words){const test=line?line+' '+word:word;if(ctx.measureText(test).width>maxWidth&&line){lines.push(line);line=word}else line=test}if(line)lines.push(line);lines.slice(0,maxLines).forEach((value,i)=>ctx.fillText(value+(i===maxLines-1&&lines.length>maxLines?'…':''),x,y+i*lineHeight));return Math.min(lines.length,maxLines)*lineHeight}
 function background(ctx,scene){const colors=scene.background?.colors||['#17265d','#a45cf2'],g=ctx.createLinearGradient(0,0,WIDTH,HEIGHT);g.addColorStop(0,colors[0]||'#17265d');g.addColorStop(1,colors[1]||'#a45cf2');ctx.fillStyle=g;ctx.fillRect(0,0,WIDTH,HEIGHT);const glow=ctx.createRadialGradient(930,150,10,930,150,500);glow.addColorStop(0,'rgba(255,214,120,.22)');glow.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=glow;ctx.fillRect(0,0,WIDTH,HEIGHT)}
 function drawArt(ctx,img){ctx.fillStyle='#05060b';ctx.fillRect(0,0,WIDTH,HEIGHT);if(!img)return;const coverScale=Math.max(WIDTH/img.width,HEIGHT/img.height),coverWidth=img.width*coverScale,coverHeight=img.height*coverScale;ctx.save();ctx.filter='blur(28px) brightness(45%) saturate(115%)';ctx.drawImage(img,(WIDTH-coverWidth)/2-35,(HEIGHT-coverHeight)/2-35,coverWidth+70,coverHeight+70);ctx.restore();const fitScale=Math.min(WIDTH/img.width,HEIGHT/img.height),fitWidth=img.width*fitScale,fitHeight=img.height*fitScale;ctx.drawImage(img,(WIDTH-fitWidth)/2,(HEIGHT-fitHeight)/2,fitWidth,fitHeight)}
 function portrait(scene){const src=scene.characterLayers?.find(c=>c.image)?.image;if(!src)return null;if(!portraitCache.has(src)){const img=new Image();img.src=src;portraitCache.set(src,img)}const img=portraitCache.get(src);return img.complete&&img.naturalWidth?img:null}
 function drawPortrait(ctx,img){if(!img)return;const x=865,y=245,w=265,h=350,scale=Math.max(w/img.width,h/img.height),sw=w/scale,sh=h/scale,sx=Math.max(0,(img.width-sw)/2),sy=Math.max(0,(img.height-sh)*.22);ctx.save();ctx.beginPath();ctx.roundRect(x,y,w,h,42);ctx.clip();ctx.drawImage(img,sx,sy,sw,sh,x,y,w,h);ctx.restore();ctx.strokeStyle='#ffe09a';ctx.lineWidth=5;ctx.beginPath();ctx.roundRect(x,y,w,h,42);ctx.stroke()}
 function centered(ctx,text,y,font,color='#fff'){ctx.font=font;ctx.fillStyle=color;ctx.textAlign='center';ctx.fillText(text,WIDTH/2,y)}
 function frame(ctx,comp,scene,img,sceneProgress,heroImg){heroImg=heroImg||portrait(scene);const art=scene.background?.image&&img;background(ctx,scene);if(art)drawArt(ctx,img);ctx.textBaseline='top';if(scene.sceneType==='title'){ctx.fillStyle='rgba(3,5,16,.58)';ctx.fillRect(0,0,WIDTH,HEIGHT);centered(ctx,'STORY SPARK CINEMA PRESENTS',120,'700 22px sans-serif','#ffe09a');centered(ctx,comp.title,235,'700 72px sans-serif','#fff');centered(ctx,`Starring ${comp.characters?.[0]?.name||'Our Hero'}`,345,'32px sans-serif','#8fe9f1');centered(ctx,'A Story Spark Cinema Original',440,'700 20px sans-serif','#ffe09a')}else if(scene.sceneType==='credits'){ctx.fillStyle='rgba(3,5,16,.7)';ctx.fillRect(0,0,WIDTH,HEIGHT);const rise=HEIGHT-(sceneProgress*(HEIGHT+520));centered(ctx,comp.title,rise,'700 64px sans-serif','#ffe09a');ctx.font='26px sans-serif';ctx.fillStyle='#fff';ctx.textAlign='center';String(scene.narration||'').split('\n').forEach((line,i)=>ctx.fillText(line,WIDTH/2,rise+110+i*46));centered(ctx,scene.dialogue||'Your Story. Your Movie. Your Magic.',rise+400,'700 26px sans-serif','#8fe9f1')}else if(!art){ctx.font='160px sans-serif';ctx.textAlign='right';ctx.fillStyle='rgba(255,255,255,.85)';ctx.fillText(scene.background?.icon||'✦',1130,95);drawPortrait(ctx,heroImg);ctx.fillStyle='rgba(2,4,13,.82)';roundRect(ctx,55,440,780,225,20);ctx.textAlign='left';ctx.fillStyle='#8fe9f1';ctx.font='700 18px sans-serif';ctx.fillText(scene.background?.name||'Movie Stage',85,466);ctx.fillStyle='#fff';ctx.font='700 42px sans-serif';ctx.fillText(scene.title||'Scene',85,500);ctx.fillStyle='#ffe6aa';ctx.font='24px sans-serif';wrap(ctx,scene.narration||scene.dialogue,85,560,700,31,3)}ctx.strokeStyle='#d8a340';ctx.lineWidth=5;ctx.strokeRect(10,10,WIDTH-20,HEIGHT-20)}
 async function musicTrack(comp){let url='',objectUrl='';try{if(comp.musicSelection==='uploaded'){const ref=comp.uploadedAudio?.find(a=>a.role==='music');if(ref){url=await AudioStore.url(ref.id);objectUrl=url}}else url=`assets/audio/music/${comp.musicSelection||'adventure'}.wav`;if(!url)return null;const context=new (window.AudioContext||window.webkitAudioContext)(),audio=new Audio(url);audio.loop=true;audio.preload='auto';const source=context.createMediaElementSource(audio),gain=context.createGain(),destination=context.createMediaStreamDestination();gain.gain.value=Math.max(0,Math.min(.7,comp.musicVolume??.35));source.connect(gain);gain.connect(destination);await context.resume();await audio.play();return {track:destination.stream.getAudioTracks()[0],audio,context,objectUrl}}catch{return null}}
 async function exportMovie(comp,hooks={}){if(active)return cancel();if(!supported()){hooks.onMessage?.('Movie export is not supported in this browser. Try the latest Edge or Chrome.');return}if(!comp?.scenes?.length){hooks.onMessage?.('This movie needs at least one scene before it can be exported.');return}const total=MovieStudio.totalDuration(comp),ui=overlay(comp.title,total),canvas=document.createElement('canvas');canvas.width=WIDTH;canvas.height=HEIGHT;const ctx=canvas.getContext('2d'),videoStream=canvas.captureStream(FPS),music=await musicTrack(comp),tracks=[...videoStream.getVideoTracks(),...(music?.track?[music.track]:[])],stream=new MediaStream(tracks),mime=['video/webm;codecs=vp9,opus','video/webm;codecs=vp8,opus','video/webm'].find(x=>MediaRecorder.isTypeSupported(x))||'',recorder=new MediaRecorder(stream,mime?{mimeType:mime,videoBitsPerSecond:5000000}:undefined),chunks=[],images=await Promise.all(comp.scenes.map(s=>image(s.background?.image)));active={cancelled:false,recorder,music};recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};const stopped=new Promise(resolve=>recorder.onstop=resolve);recorder.start(1000);const started=performance.now();await new Promise(resolve=>{const tick=()=>{if(!active||active.cancelled)return resolve();const elapsed=(performance.now()-started)/1000;if(elapsed>=total)return resolve();let before=0,index=0;for(;index<comp.scenes.length;index+=1){if(elapsed<before+comp.scenes[index].duration)break;before+=comp.scenes[index].duration}index=Math.min(index,comp.scenes.length-1);const scene=comp.scenes[index],within=(elapsed-before)/Math.max(1,scene.duration);frame(ctx,comp,scene,images[index],within);update(ui,elapsed/total*100,`Rendering scene ${index+1} of ${comp.scenes.length} • ${format(elapsed)} / ${format(total)}`);requestAnimationFrame(tick)};tick()});recorder.stop();await stopped;music?.audio.pause();music?.track.stop();await music?.context.close();if(music?.objectUrl)URL.revokeObjectURL(music.objectUrl);videoStream.getTracks().forEach(t=>t.stop());const wasCancelled=active?.cancelled;active=null;if(wasCancelled){closeOverlay();hooks.onMessage?.('Movie export cancelled.');return}update(ui,100,'Movie ready! Starting download…');const blob=new Blob(chunks,{type:recorder.mimeType||'video/webm'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=escFile(comp.title)+'.webm';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),30000);setTimeout(closeOverlay,900);hooks.onMessage?.('🎬 Your movie was exported!')}
 function format(sec){const n=Math.max(0,Math.floor(sec));return `${Math.floor(n/60)}:${String(n%60).padStart(2,'0')}`}
 function safe(s){return String(s??'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
 window.MovieExporter={export:exportMovie,cancel,supported,get active(){return !!active}};
})();
